### ISSUE TITLE
Skyrim Egg crashes

### ISSUE THREAD

**Issue by killertobyd** [Technoguyfication/SkyrimTogether-Egg#2]
Hi @Technoguyfication 
since a few days always comes this error.

![Unbenannt](https://user-images.githubusercontent.com/96026375/191377903-d1c644c7-3ce6-4b14-823c-25527c69a5d7.PNG)

**Comment by rainerstudios** [comment]
Getting the same error..Any Fix?

**Comment by MrPranklez** [comment]
Running into the same issue, but I did some digging.

It appears to be caused when running ubuntu 22.X

**Comment by Brandon-Odom** [comment]
I hate to zombie a thread, however, for anyone else running Ubuntu 22.X that happens across this issue. I changed the docker Image under the egg's 'Configuration' tab to use 'ghcr.io/goover/ubuntu:22-jammy.' Once deployed the egg I chose that as the Docker Image under the 'Startup' Tab along with any other server configurations such as 'difficulty' and 'XP Sync.' Then I started the server for the first time and it booted.

**Comment by killertobyd** [comment]
I have fixed this myself 4 months ago was just a little inactive sry
